###############################################################################
###  File yml : Contain some global information for the project ###
###############################################################################

# Insert information for Database here:
# Example:

DB:
  host: "localhost"
  user: "username"
  password: "yourpassword"
  database: "databasename"


API: 
  url : "https://fr.openfoodfacts.org/cgi/search.pl?"


PAYLOAD:
  action: "process"
  tagtype_0: "categories"  
  tag_contains_0: "contains"
  tag_0: ""
  page_size: 500
  json: True

CATEGORIES: ["Pizzas", "Snacks", "Viandes", "Produits laitiers", "Graines"]